spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat_picture?serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
      database: mysql
  config:
    import: optional:file:.env[.properties]

cat-api:
  key: ${CAT_API_KEY}
  url: ${CAT_API_URL}

logging:
  level:
    com.ys.cat_picture.infra.client: DEBUG